# Generated by Django 4.2.7 on 2026-06-19 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('a_pos', models.IntegerField(default=0, verbose_name='A+')),
                ('a_neg', models.IntegerField(default=0, verbose_name='A-')),
                ('b_pos', models.IntegerField(default=0, verbose_name='B+')),
                ('b_neg', models.IntegerField(default=0, verbose_name='B-')),
                ('ab_pos', models.IntegerField(default=0, verbose_name='AB+')),
                ('ab_neg', models.IntegerField(default=0, verbose_name='AB-')),
                ('o_pos', models.IntegerField(default=0, verbose_name='O+')),
                ('o_neg', models.IntegerField(default=0, verbose_name='O-')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloodbank_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
