# Generated by Django 4.2.7 on 2026-06-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_bloodrequest_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorresponse',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
