# Generated by Django 4.2.7 on 2026-06-19 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_address_hospital_city_hospital_latitude_and_more'),
        ('requests_app', '0003_remove_donorresponse_is_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('bed_type', models.CharField(choices=[('ICU', 'ICU'), ('Oxygen', 'Oxygen'), ('General', 'General')], max_length=20)),
                ('emergency_notes', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_requests', to='hospitals.hospital')),
            ],
        ),
    ]
