# Generated by Django 4.2.30 on 2026-06-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_bedrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedrequest',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email for status updates', max_length=254, null=True),
        ),
    ]
