# Generated by Django 4.2.30 on 2026-06-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_emergencyalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergencyAlert',
        ),
    ]
