# Generated by Django 4.2.30 on 2026-06-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hospital', 'Hospital'), ('bloodbank', 'Blood Bank'), ('donor', 'Donor / Regular User')], default='donor', max_length=20),
        ),
    ]
