# Generated by Django 4.2.30 on 2026-06-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospitalreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct URL to a hospital image', null=True),
        ),
    ]
